language: node_js
node_js:
  - node
install:
  - yarn global add codecov
  - yarn
script:
  - yarn lint
  - yarn format:check
  - yarn test --coverage --verbose
  - yarn build
  - git diff --exit-code --name-only
  - codecov
deploy:
  provider: npm
  email: se.mo.moosavi@gmail.com
  api_key:
    secure: kfUXRyhVHSNOFbeugpThSS71EXjpl9V+vVfMU0AgLuqrqmr4nQH4HMFs5R5dAQLEk4KTbmP0zwjRjS9qzSA7S0suV32I/MR2l1eL6FidHkULCmdZi2IzF9I8gyn6/Mklg8SkihfDfLiRNEpxD7FPKJnXe/UvEbyl0Mf+q2ZocHRdFGXbMhkog3UXorVZgI+fS/OgeceY591yyicgP+8p7yUhfpQByf6m+xjwq2UuB7RSInxHFVRQ0WnOPX+dU8ByZuXP3+lXLXn4e90sXev3iSWQQmUacBR7GFf0wH1omvCAGbH7x6D5kMPwPyROHXJzbv2UPR8rTtmCMEiJoAbcT2IGJ5Pa4bbymxLmLfSmjT9hgfbZN04RswiYro6AMynLrOJxJvFHh9mDprv84uUdbSajSUZTjTwxMgtUn9ipsUQ10xVRT1xeHdKpRPgIKCdF6V+4X1L1SlugUYXYIwwMh4kOBrYYVebHHEetjBfGde3gLCDjBlbFZDNC/EPUv709wLRaaKu+5adGp0Kp6I6WvRJ5ofbaX/ew3zhfPTezXeRHEAbkxDRgo6Yd6eYIvZv2Rb3pdWUE8WRClqHcQrWw3o9vY0bm8jPNZGzHUHL1lJYYgSao68QQ4UPR0pvfM2R71Rj1b4nzT2Do+ZNVarHbODzMhvuItlwox8pmP7zFSbE=
  on:
    tags: true
    repo: sahabpardaz/ctablex
  skip_cleanup: 'true'
